#!/bin/bash

if [ -z "$1" ]; then echo "❌ Usage: $0 EMAIL"; exit 1; fi

node <<EOF
import { createClient } from "@supabase/supabase-js";
const client = createClient("$(<~SUPABASE_URL)", "$(<~SUPABASE_SERVICE_ROLE_KEY)");
console.log((await client.auth.admin.generateLink({ email: '$1', options: { redirectTo: 'http://127.0.0.1:8080' }, type: 'magiclink' })).data.properties.action_link)
EOF
