#!/bin/bash

if [ -z "$1" ]; then echo "❌ Usage: $0 EMAIL"; exit 1; fi

OUTPUT=$(
node <<EOF
import { createClient } from "@supabase/supabase-js";
const client = createClient("$(<~SUPABASE_URL)", "$(<~SUPABASE_SERVICE_ROLE_KEY)");
console.log((await client.auth.admin.generateLink({ email: '$1', options: { redirectTo: 'https://www.orthogonalthinker.com/investor/' }, type: 'magiclink' })).data.properties.action_link)
EOF
)

echo $OUTPUT

if command -v "xclip" >/dev/null 2>&1; then
  echo $OUTPUT | xclip -selection clipboard
  echo "COPIED TO CLIPBOARD"
fi
