export {
  ChevronUp as IconAdmin,
  UserAvatar as IconAvatar,
  Information as IconInfo,
  // Account as IconInvestment,
  // Apps as IconDocument,
  Chat as IconRequest,
  Delete as IconDelete,
  Document as IconDocument,
  // Edit as IconEdit,
  Login as IconLogin,
  Logout as IconLogout,
  // Menu as IconInvestment,
  Money as IconInvestment,
  Settings as IconEdit,
  // Unlink as IconUnlink,
  // UserAvatar as IconUserAvatar,
  CloudUpload as IconUpload,
  StatusChange as IconStatus,
  Send as IconSend,
  ArrowLeft as IconLeft,
  Image as IconFileTypeImage,
  Document as IconFileTypeDocument,
  DocumentUnknown as IconFileTypeUnknown,
  Copy as IconCopy,
} from "@vicons/carbon"; // https://xicons.org/
